FROM apache/airflow
LABEL authors="mike"
USER root

ENV ACCEPT_EULA=Y

RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean \
    && apt update \
    && apt upgrade -y \
    && apt install nano -y

USER 1001

COPY src /app