services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 50m
        max-file: 10

  webserver:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres
      - scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
    volumes:
      - ./logs:/opt/airflow/logs
    ports:
      - "8085:8080"
    entrypoint: [ "airflow", "webserver" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:8080/health" ]
      interval: 30s
      retries: 3

  scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    entrypoint: [ "airflow", "scheduler"] #"db", "init" ] # the DB must be init first.  Uncomment, then run original
    # Notes: users don't exist by default.  Create one (in an attached terminal)
    #    airflow users \
    #    create --role Admin \
    #    --username admin \
    #    --email admin \
    #    --firstname admin \
    #    --lastname admin \
    #    --password admin


    # Start the schedular:
    # airflow scheduler

  redis:
    image: redis
volumes:
  postgres_data:

