version: '3.8'

services:
  python-debug:
    image: sss-python-dev:latest
    build:
      context: ..
      dockerfile: Dockerfile.symbol.java.airflow.template-sss-python-dev
    env_file:
      - "../.env"
    environment:      # This section overrides the .env file declarations
      - VAR=VAL
    stdin_open: true  # Keeps the container open even if not attached
    tty: true         # Allocates a pseudo-TTY for the container