services:

  sss_portainer:
    image: portainer/portainer-ce:2.21.0
    container_name: sss_portainer
    hostname: sss_portainer
    domainname: sss_portainer.home.lan
    restart: always
    ports:
      - 8088:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  sss_postgres:
    image: postgres:16.3
    container_name: sss_postgres
    hostname: sss_postgres
    domainname: sss_postgres.home.lan
    depends_on:
      - sss_portainer
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schemas:/var/lib/postgresql/schemas
    logging:
      options:
        max-size: 50m
        max-file: 10

  sss_webserver:
    image: apache/airflow:2.9.3
    container_name: sss_webserver
    hostname: sss_webserver
    domainname: sss_webserver.home.lan
    depends_on:
      - sss_scheduler
      - sss_portainer
    env_file:
      - ".env"
    volumes:
      - ./logs:/opt/airflow/logs
    ports:
      - "8888:8080"
      - "9443:9443"
    entrypoint: [ "airflow", "webserver" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:8080/health" ]
      interval: 30s
      retries: 3

  sss_scheduler:
    image: apache/airflow:2.9.3
    container_name: sss_scheduler
    hostname: sss_scheduler
    domainname: sss_scheduler.home.lan
    depends_on:
      - sss_postgres
      - sss_portainer
    env_file:
      - ".env"
    volumes:
      - ./src/main/python/dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./libs:/opt/airflow/libs
    entrypoint: [ "airflow", "scheduler"]
    # entrypoint: [ "airflow", "db", "init" ] # the DB must be init first.
    # Notes: users don't exist by default.  Create one (in an attached terminal)
#        airflow users \
#        create --role Admin \
#        --username admin \
#        --email admin \
#        --firstname admin \
#        --lastname admin \
#        --password admin
    # Permission error? sudo chown 50000:0 dags logs plugins

    # Start the schedular:
    # airflow scheduler

volumes:
  postgres_data:
  portainer_data:
#    external: true
#    name: portainer_data
