name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bacongobbler/azure-blob-storage-upload@v3.0.0
        with:
          source_dir: dags
          container_name: dags
          # connection_string: ${{ secrets.ConnectionString }}
          # extra_args: '--pattern *.tar.gz'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
